### ISSUE TITLE
Error with flutter 3 but works fine with flutter 2.10.5 and other

### ISSUE THREAD

**Issue by Manishmg3994** [AgoraIO/Agora-Flutter-SDK#679]
```
**how to solve this**
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraRtcEnginePlugin.kt: (251, 18): Type mismatch: inferred type is String? but String was expected
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraSurfaceViewFactory.kt: (16, 1): Class 'AgoraSurfaceViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraSurfaceViewFactory.kt: (20, 3): 'create' overrides nothing
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraTextureViewFactory.kt: (12, 1): Class 'AgoraTextureViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: C:\src\flutter\.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraTextureViewFactory.kt: (17, 3): 'create' overrides nothing
```

**Comment by rpksharma** [comment]
Same issue here, plz fix it

**Comment by vpositron** [comment]
The same issue... (

**Comment by zubisofts** [comment]
Same here, please fix.

**Comment by littleGnAl** [comment]
Duplicated https://github.com/AgoraIO/Agora-Flutter-SDK/issues/677

**Comment by famarrero** [comment]
i have the same problem, any solution?

**Comment by ShaimPatel** [comment]
Same Issue, Please anyone solve this

>
