### ISSUE TITLE
Execution failed for task ':agora_rtc_engine:compileDebugKotlin'.

### ISSUE THREAD

**Issue by smit-sk** [AgoraIO/Agora-Flutter-SDK#666]
I have same issue.
e: C:\src\flutter.pub-cache\hosted\pub.dartlang.org\agora_rtc_engine-5.1.0\android\src\main\kotlin\io\agora\agora_rtc_engine\AgoraTextureViewFactory.kt: (17, 3): 'create' overrides nothing

FAILURE: Build failed with an exception.

What went wrong:
Execution failed for task ':agora_rtc_engine:compileDebugKotlin'.
Compilation error. See log for more details

Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

Get more help at https://help.gradle.org/

BUILD FAILED in 40s
Exception: Gradle task assembleDebug failed with exit code 1

**Comment by littleGnAl** [comment]
Seems related issue https://github.com/AgoraIO/Agora-Flutter-SDK/issues/623

**Comment by ShawermaBox** [comment]
are you on flutter dev channel?
If so, switching to the stable channel solved the problem for me

**Comment by dhimanrascon** [comment]
I'm facing same issue, after upgrading to flutter latest stable version 3.0.0 & agora latest version 5.1.0

Here is the log 

```
e: /flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-5.1.0/android/src/main/kotlin/io/agora/agora_rtc_engine/AgoraRtcEnginePlugin.kt: (251, 18): Type mismatch: inferred type is String? but String was expected
e: /flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-5.1.0/android/src/main/kotlin/io/agora/agora_rtc_engine/AgoraSurfaceViewFactory.kt: (16, 1): Class 'AgoraSurfaceViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-5.1.0/android/src/main/kotlin/io/agora/agora_rtc_engine/AgoraSurfaceViewFactory.kt: (20, 3): 'create' overrides nothing
e: /flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-5.1.0/android/src/main/kotlin/io/agora/agora_rtc_engine/AgoraTextureViewFactory.kt: (12, 1): Class 'AgoraTextureViewFactory' is not abstract and does not implement abstract base class member public abstract fun create(p0: Context?, p1: Int, p2: Any?): PlatformView defined in io.flutter.plugin.platform.PlatformViewFactory
e: /flutter/.pub-cache/hosted/pub.dartlang.org/agora_rtc_engine-5.1.0/android/src/main/kotlin/io/agora/agora_rtc_engine/AgoraTextureViewFactory.kt: (17, 3): 'create' overrides nothing

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':agora_rtc_engine:compileDebugKotlin'.
> Compilation error. See log for more details

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 32s
```

**Comment by juanmanuel0963** [comment]
This error started when I upgraded flutter to 3.0.0
I've downgraded flutter to 2.10.5 and It's working fine now.

1- Download flutter 2.10.5 from https://docs.flutter.dev/development/tools/sdk/releases
![image](https://user-images.githubusercontent.com/44442325/168511274-e03df0b8-6839-4e3c-a309-e4e965c2760a.png)

2- Edit environment variables pointing to your flutter 2.10.5 folder
![image](https://user-images.githubusercontent.com/44442325/168511334-af9b4b98-581e-45f8-8d57-6464444436bf.png)

3- Execute some commands to test solution
flutter channel stable  
flutter --version 
flutter build apk --debug
flutter build apk --profile
flutter run
![image](https://user-images.githubusercontent.com/44442325/168512233-f167ebed-64f5-4373-ace0-4265abd16862.png)

**Comment by ShawermaBox** [comment]
or just use `flutter downgrade v2.10.5` in the terminal
